export const FSQUARE_CLIENT_ID = "Q5MK2XFDK3FVTDQLOQKSFTKS1CI1XEWZSO2TIPP5DU2PWICK";
export const FSQUARE_CLIENT_SECRET = "MQ3CZLR5KY1F04FUAX5YWXOLYRRJSYFWCHZANZZ23M4WI05L";
export const GOOGLE_MAPS_KEY = "AIzaSyACbjbDtFHboToWICX5E4bAbdInVNk5D1Y";
